### ISSUE TITLE
yuedajiong-question #05: how about the encoding space design?  advanced or limited?

### ISSUE THREAD

**Issue by yuedajiong** [facebookresearch/ijepa#10]
just from my limited understanding:

as we can see, from paper and in code, the mask is created in dataset creation, that means the mask in original 2d pixel space.

even encoded, that is, after encoder(input-side) and before predictor, the mask used is still raw mask, in Euclidean space/2D/pixel.

even if no hierarchical encoder so far, that still limited the tranfrorming-ability/mapping-ability/degree-of-freedom of encoder, we must keep somthing<not only form/shape, but also semantic> and we can recognize/use it after encoding, that is,  can apply mask after encoding.  

is this the best design?
no any other design that mapping mask to another more abstract space?  or if we can not design a correct mask-mapping, can we use other fulcrum for self-supervised.

just from my view, the raw,cann't-mapping mask is more limited, especial for later hierarchical encoders in LeCun's total-JEPA.

in a word,  on the one hand, we want to constuct loss in laten-space after encoders,  on the other hand, we still use original pixel space mask after encoders, for self-supervised.       right?  awkward?

**Comment by MidoAssran** [comment]
Hi @yuedajiong,

The masks indicate to the model which tokens to keep. This is really just a 1D integer list since vision transformers are fed a flattened sequence of patches. While you can think of a correspondence to 2D euclidean pixel space, you can also generalize this to masking tokens in latent space, so this is fine from a generality point of view and extending the approach to hierarchical prediction.

Having said that, it is incredibly interesting to consider how your masking strategy should change when doing hierarchical latent space prediction, as the structure of the latent space will now result in the masking of features, rather than raw 2D pixels. We have not explored this yet in this work, but I think this is an exciting direction for future research.
