### ISSUE TITLE
yuedajiong-question #01:  no hierarchical? 

### ISSUE THREAD

**Issue by yuedajiong** [facebookresearch/ijepa#6]
no hierarchical encoder(input-side) and predictor?  (I can see the hierarchical design in LeCun's 10 years plan)  

do we need explicit hierarchical encoder and predictor?  or current one level encoder(i think it is a type of weakened/implicit hierarchical encoding, different level abstraction is based on residual of transformer).    

if hierarchical encoder and predictor (encode to different abstraction levels, and predict),  do we need hierarchical target_encoder?

**Comment by MidoAssran** [comment]
Hi @yuedajiong, right now, I-JEPA is not hierarchical, but we definitely plan to investigate building hierarchical prediction into the approach! The idea would be to apply the I-JEPA loss at several layers throughout the network rather than just at the end of the trunk (i.e., from one layer predicting the target encoder activations at a similar layer). I think it makes sense to have separate predictors for each level of the hierarchy.
